let datasors = [
  {
    nov: "terevez",
    ad: "kelem",
    qiymet: 3,
    vahid: "kg",
    src: "https://th.bing.com/th/id/Ra1239ae9151283781ab42cafd7ca9658?rik=ctPrY0zXWZc1jg&pid=ImgRaw",
  },
  {
    nov: "terevez",
    ad: "kartof",
    qiymet: 1,
    vahid: "kg",
    src: "images/kartof.jpg",
  },
  {
    nov: "terevez",
    ad: "pomidor",
    qiymet: 2,
    vahid: "kg",
    src: "",
  },
  {
    nov: "terevez",
    ad: "sogan",
    qiymet: 0.5,
    vahid: "kg",
    src: "",
  },
  {
    nov: "terevez",
    ad: "badimcan",
    qiymet: 1,
    vahid: "kg",
    src: "",
  },
  {
    nov: "meyve",
    ad: "alma",
    qiymet: 1,
    vahid: "kg",
    src: "",
  },
  {
    nov: "meyve",
    ad: "armud",
    qiymet: 2,
    vahid: "kg",
    src: "",
  },
  {
    nov: "meyve",
    ad: "banan",
    qiymet: 2.2,
    vahid: "kg",
    src: "",
  },
  {
    nov: "sirniyyat",
    ad: "sokalad",
    qiymet: 1.5,
    vahid: "kg",
    src: "",
  },
  {
    nov: "sirniyyat",
    ad: "konfet",
    qiymet: 1,
    vahid: "kg",
  },
  {
    nov: "sirniyyat",
    ad: "pecenye",
    qiymet: 1,
    vahid: "eded",
  },
  {
    nov: "un memulatlari",
    ad: "corek",
    qiymet: 0.5,
    vahid: "eded",
  },
  {
    nov: "un memulatlari",
    ad: "koke",
    qiymet: 1,
    vahid: "eded",
  },
  {
    nov: "un memulatlari",
    ad: "qogal",
    qiymet: 3,
    vahid: "kg",
  },
  {
    nov: "un memulatlari",
    ad: "lavas",
    qiymet: 0.5,
    vahid: "eded",
  },
  {
    nov: "ickiler",
    ad: "fanta",
    qiymet: 1,
    vahid: "eded",
  },
  {
    nov: "ickiler",
    ad: "kola",
    qiymet: 1.5,
    vahid: "eded",
  },
  {
    nov: "ickiler",
    ad: "sirab",
    qiymet: 1,
    vahid: "eded",
  },
  {
    nov: "dondurma",
    ad: "plombir",
    qiymet: 3,
    vahid: "kg",
  },
  {
    nov: "dondurma",
    ad: "magnum",
    qiymet: 3,
    vahid: "kg",
  },
  {
    nov: "dondurma",
    ad: "panda",
    qiymet: 3,
    vahid: "kg",
  },
  {
    nov: "edviyyatlar",
    ad: "duz",
    qiymet: 3,
    vahid: "kg",
  },
  {
    nov: "edviyyatlar",
    ad: "istiot",
    qiymet: 3,
    vahid: "kg",
  },
  {
    nov: "edviyyatlar",
    ad: "sarikok",
    qiymet: 3,
    vahid: "kg",
  },
  {
    nov: "konservalar",
    ad: "kilke",
    qiymet: 2,
    vahid: "eded",
  },
];
